import './globals.scss';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Suspense } from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div style={{ display: 'flex', flexDirection: 'column', minHeight: '100vh' }}>
                    <div className="header">
                        <div className="header-title">
                            <h1>Brewerys</h1>
                            A brewerys list by Ope Brewery DB

                        </div>
                    </div>
                    {/* <Suspense fallback={<p>Loading</p>}> */}
                    <main className="main">
                        {children}
                    </main>

                    {/* </Suspense> */}
                    <div className="footer">
                        <span>Brewery List</span>
                    </div>
                </div>
            </body>

        </html>
    );
}
